spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_shopping
    username: root
    password: root
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

